version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.1.0
    container_name: skywalking-es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  # elastichd:
  #     image: containerize/elastichd
  #     container_name: elasticsearch-ui
  #     depends_on:
  #         - elasticsearch
  #     ports:
  #         - 9800:9800
  #     links:
  #         - elasticsearch:demo

  oap:
    image: apache/skywalking-oap-server
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      #- JAVA_OPTS: "-Xms2048m -Xmx2048m"
  ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 18080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
