version: '2'

services:
  kafka-zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.41.200
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
    depends_on:
      - kafka-zookeeper

  # kafka 图形界面
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: kafka-zookeeper:2181
    depends_on:
      - kafka-zookeeper
      - kafka
