server:
  port: 8765
spring:
  aop:
    proxy-target-class: true
  application:
    name: lli-cloud-admin
  output:
    ansi:
      enabled: always
    # 添加安全认证
  security:
    user:
      name: ${LOGIN_NAME:admin}
      password: ${LOGIN_PWD:admin}

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_ADDRESS:localhost}:7001/eureka/
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_NAME:localhost}:7001/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #eureka客户端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 20
    #eureka服务端在收到最后一次心跳等待的时间上线，默认90s
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      user.mame: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
