server:
  port: 8891
spring:
  aop:
    proxy-target-class: true
  application:
    name: lli-cloud-ftp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force-request: true
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb://vm-1.lli.com:27017/FILE_SERVER

# ============================ eureka===============================
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_ADDRESS:localhost}:7001/eureka/
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_NAME:localhost}:7001/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #eureka客户端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 20
    #eureka服务端在收到最后一次心跳等待的时间上线，默认90s
    lease-expiration-duration-in-seconds: 30
# ============================ consul===============================
# ============================ nacos===============================
# ============================ FTP===============================
storage:
  type: ftp
  download-path: downloadPath/
  upload-path: uploadPath/
  preview-path: preview/
  temp-path: tempPath/
  video-path: videopath/
#
ftp:
  host: vm-1.lli.com
  port: 21
  user-name: ftplli
  user-password: ftplli
oss:
  accessKeyId: LTAIAx9GPnernwbD
  accessKeySecret: ZibEXmLHrPH3ycyJUUBnNfAbKHspGC
  bucketName: demo-standard
  comBucketName: lc-public-static
  endpoint: http://oss-cn-beijing.aliyuncs.com
  publicUrlPrefix: https://lc-public-static.oss-cn-beijing.aliyuncs.com

