server:
  port: 7501
spring:
  application:
    name: lli-cloud-sso-security-cas-client
################################################################################################################
###Spring Security Cas 相关配置：
################################################################################################################
# 权限控制
security-cas:
  # 系统标识
  system-id: 0
  # 默认路径拦截规则定义,hasAnyRole处理的时候 默认会拼接 "ROLE_",所以roles规则不允许以 ROLE_开头
  filter-chain-definition-map:
    '[/]': anon
    '[/**/favicon.ico]': anon
    '[/error*]': anon
    '[/swagger-ui.html**]': anon
    '[/swagger-resources/**]': anon
    '[/doc.html]': anon
    '[/v2/**]': anon
    '[/v2/api-docs]': anon
    '[/logout]': anon
    '[/ipAddr/*]': ipaddr[192.168.1.0/24]
    '[/hello]': roles[guest,admin]
    '[/test/*]': roles[BASE_ROLE]
    '[/admin/*]': perms[admin]
  # 不需要登录验证的路径
  ignore-pattern:
    - /healthCheck
### Cas 配置
cas:
  server-url-prefix: http://localhost:8080/cas
  server-login-url: http://localhost:8080/cas/login
  client-host-url: http://localhost:${server.port}
  accept-any-proxy: true
  single-logout:
    enabled: true
  proxy-callback-url: http://localhost:${server.port}/proxy/callback
  proxy-receptor-url: /proxy/callback
  allowed-proxy-chains: /*
  attribute-authorities: user_name