server:
  port: 7301
spring:
  application:
    name: lli-cloud-sso-cas-client
##### Cas 相关配置
cas:
  server-url-prefix: http://localhost:8080/cas
  server-login-url: http://localhost:8080/cas/login
  client-host-url: http://localhost:${server.port}
  accept-any-proxy: true
  single-logout:
    enabled: true
  proxy-callback-url: http://localhost:${server.port}/proxy/callback
  proxy-receptor-url: /proxy/callback
  allowed-proxy-chains: /*
##### Cas url authc 配置
cas-authc:
  ignore-pattern:
    - /healthCheck
    - /test/*


