server:
  port: 7201
spring:
  application:
    name: lli-cloud-eureka-consume

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    #  Eureka-Client端拉取 Server注册信息的频率,默认30秒
    registry-fetch-interval-seconds: 10
    ## InstanceInfoReplicator 将实例信息变更同步到 Eureka Server的初始延迟时间 ，默认为40秒
    initial-instance-info-replication-interval-seconds: 10
    ## http 连接超时时间，默认为5秒，这里设置为30秒
    eureka-server-connect-timeout-seconds: 30
    service-url:
      #      defaultZone: http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_ADDRESS:localhost}:7001/eureka/
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_NAME:localhost}:7001/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #eureka客户端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 20
    #eureka服务端在收到最后一次心跳等待的时间上线，默认90s
    lease-expiration-duration-in-seconds: 30