server:
  port: 7101
spring:
  application:
    name: lli-cloud-eureka-provide

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_ADDRESS:localhost}:7001/eureka/
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://${LOGIN_NAME:lli}:${LOGIN_PWD:lli}@${EUREKA_SERVER_NAME:localhost}:7001/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #eureka客户端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 20
    #eureka服务端在收到最后一次心跳等待的时间上线，默认90s
    lease-expiration-duration-in-seconds: 30