# 端口
server:
  port: 8010
# 应用名称
spring:
  application:
    name: lli-cloud-fastdfs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://t420.lli.com:27017/file-index

# logging日志
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

# FastDFS 相关配置
fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
    - huashuo.lli.com:22122
