# 端口
server:
  port: 8010
# 应用名称
spring:
  application:
    name: lli-cloud-fastdfs
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://vm-1.lli.com:27017/file-index
# FastDFS 相关配置
fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
    - vm-1.lli.com:22122